### ISSUE TITLE
图表可否支持监听滚动事件

### ISSUE THREAD

**Issue by anyanf** [hydreamit/HyCharts#1]
图表可否支持监听滚动事件。
因为k线图可能特别打，想分块加载。

**Comment by hydreamit** [comment]
已添加：

/// 滚动事件
@property (nonatomic, copy) void(^scrollAction)(CGFloat contentOffset, CGFloat chartWidth, CGFloat chartContentWidth);

**Comment by anyanf** [comment]
非常感谢，稍后我试试哈。。

**Comment by anyanf** [comment]
您好，在用的过程中发现一些问题想向您请教一下，可否加个微信，我的微信号：Daydreamer-An。。
1. 如何自动缩放到可以显示所有数据的大小。
2. 是否支持拼接数据。
3. 点击之后是否可以直接返回model，index也可以，或者开放计算index的接口

**Comment by anyanf** [comment]
disPlayMaxMinPrice无法控制最高最底价是否显示
