### ISSUE TITLE
实时刷新

### ISSUE THREAD

**Issue by LiuBoPOP** [hydreamit/HyCharts#14]
如何只刷新最新的蜡烛图？

**Comment by hydreamit** [comment]
改变数据源block里面 第一个数据实体数据 或者 添加删除最前面的实体   调用 refreshChartsView 方法

**Comment by LiuBoPOP** [comment]
在刷新最新的蜡烛图的时候 左右滑动主图会崩溃到这句[((HyChartKLineMainLayer *)self.chartLayer) renderingNewprice];

**Comment by hydreamit** [comment]
使用最新版本HyChartViewProtocol里面的 refreshChartsView方法

**Comment by hydreamit** [comment]
能使用的方法和属性都在暴露给外界的协议里面 不要直接调用实体类.h文件的方法

**Comment by LiuBoPOP** [comment]
现在调用的就是refreshChartsView这个方法。在滑动scrollView时 可现实的数组中不包括第一条数据 然后就走refreshChartsView方法中的completion:^{}方法 这里面有个刷新最新价的方法[((HyChartKLineMainLayer *)self.chartLayer) renderingNewprice]; 在滑动后 就会崩溃在这一句 我看了一下当时的self.chartLayer 不属于HyChartKLineMainLayer这个类 找不到renderingNewprice这个方法 所以崩溃的

**Comment by LiuBoPOP** [comment]
现在调用的就是refreshChartsView这个方法。在滑动scrollView时 可显示的数组中不包括第一条数据 然后就走refreshChartsView方法中的completion:^{}方法 这里面有个刷新最新价的方法[((HyChartKLineMainLayer *)self.chartLayer) renderingNewprice]; 在滑动后 就会崩溃在这一句 我看了一下当时的self.chartLayer 不属于HyChartKLineMainLayer这个类 找不到renderingNewprice这个方法 所以崩溃的

**Comment by hydreamit** [comment]
用的是HyChartKLineView这个类吗

**Comment by LiuBoPOP** [comment]
是的

**Comment by hydreamit** [comment]
已修改
