### ISSUE TITLE
发现一个在.mm文件中使用的bug

### ISSUE THREAD

**Issue by DonnyHe** [hydreamit/HyCharts#15]
用pod添加到项目中，然后一直报这个错：Right operand to ? is void, but left operand is of type 'int'
很奇怪的问题，xcode定位是HyChartsMethod.h的第25行，!block ?: block()。
因为项目中存在大量的.mm文件，倒腾了很久，然后我自己试了一下，在.m文件下，这个写法不会报错，在.mm文件下，就通过不了。能否将其改为通用普通写法，增强一下兼容性。

**Comment by DonnyHe** [comment]
多次测试，1.0.2和1.0.1都会报错，只要在.mm文件引用这个库就会报错，但是1.0.0就不会报错。对比了一下，1.0.0是包含HyChartsMethod.h和HyChartsMethod.m文件的，1.0.1和1.0.2是只有HyChartsMethod.h文件，方法是CG_INLINE 宏定义的。太奇怪了，为何宏定义的就不支持这种写法···

**Comment by hydreamit** [comment]
已改

**Comment by DonnyHe** [comment]
> 已改

能否更新一个1.0.3到pod，感谢感谢

**Comment by DonnyHe** [comment]
> 已改

能否更新下pod版本，感谢
