### ISSUE TITLE
横屏切换重设frame的问题

### ISSUE THREAD

**Issue by DonnyHe** [hydreamit/HyCharts#17]
<img width="901" alt="QQ20200902-210401@2x" src="https://user-images.githubusercontent.com/16313938/91987171-4a744a80-ed60-11ea-98f4-3597b099c4cd.png">
我在横屏的时候重设了KlineView的frame，横屏后显示出来的蜡烛图的宽度和竖屏的宽度一样，右面增加的宽度范围内绘制不出来，不过指数都正确显示了，请问这个该怎么解决一下呢？

**Comment by hydreamit** [comment]
已解决 如果只是改变图frame 不需要调用setNeedsRendering 如果改变了图表其他配置需要调用setNeedsRendering
