### ISSUE TITLE
关于手势

### ISSUE THREAD

**Issue by mantoo96** [hydreamit/HyCharts#18]
大佬你好
if (!self.pinchGestureDisabled && !self.pinchGesture.view) {
        [self.scrollView addGestureRecognizer:self.pinchGesture];
    }
在图表数据很少的时候，手势只能在有数据的图表上。怎么才能让手势一直在全图表上？

**Comment by mantoo96** [comment]
啊，之前以为是只添加到有数据部分，后来发现在下面做了这个判断
if (index < self.dataSource.modelDataSource.models.count) {
}
把这个注释了就行了。不过有什么问题吗？

**Comment by hydreamit** [comment]
没有问题 这个缩放的index 是算缩放中心的 和数据没关系 -- 内部设计是手指位置有图表才能缩放 要满足你的需求可以把那个那个判断去掉
