### ISSUE TITLE
HyChartKLineModel .cxx_destruct crash

### ISSUE THREAD

**Issue by DonnyHe** [hydreamit/HyCharts#19]
看到Bugly记录了crash信息：
<img width="993" alt="QQ20201010-175722@2x" src="https://user-images.githubusercontent.com/16313938/95652272-75ea1200-0b22-11eb-9ff8-d1a7eb09d35d.png">
因为我改动了部分东西，所以我本地HyChartView第499行代码是：
<img width="937" alt="QQ20201010-175749@2x" src="https://user-images.githubusercontent.com/16313938/95652297-9f0aa280-0b22-11eb-8f97-5526a66bbabd.png">
HyChartKLineModel第43行代码是：
<img width="353" alt="QQ20201010-175833@2x" src="https://user-images.githubusercontent.com/16313938/95652312-aaf66480-0b22-11eb-9c6f-48e4c436b5e0.png">

不知这个crash的原因是什么，还请作者赐教

**Comment by hydreamit** [comment]
分时线数据是怎么配置的？

/*
 分时图线条设置 默认是一条线 ---->  @[收盘价]
 */
/// 自定义 方式一  直接赋值
@property (nonatomic, strong) NSArray<NSNumber *> *values;
/// 分时线断点设置, 默认为NO  —— @(YES) \ @(NO)
@property (nonatomic, strong) NSArray<NSNumber *> *breakpoints;
/// 自定义 方式 二  根据K线处理后数据设置
- (void)configTimeLineValues:(void (^)(id<HyChartKLineModelProtocol> _model))block;

**Comment by DonnyHe** [comment]
我关闭了分时线功能，所以没有配置分时线数据
