### ISSUE TITLE
股票类图标下方的时间位置计算问题

### ISSUE THREAD

**Issue by mantoo96** [hydreamit/HyCharts#2]
autoSetText = YES，或者默认YES
第一个时间和最后一个时间超出屏幕


**Comment by hydreamit** [comment]
文字中心默认与轴线对齐, 可以根据需求设置偏移量

/// 轴上文字偏移量
@property (nonatomic, assign) CGPoint axisTextOffset;

**Comment by mantoo96** [comment]
感谢大佬的回复，之前看到了这个参数，调用无效以为是没完善的地方。进去发现HyChartAxisTextPositionPlus类型，x轴默认一直都是0。现在改好了
