### ISSUE TITLE
k线刷新，如何做。有文档说明吗，希望能更新一下（点击按钮加入一条k线）

### ISSUE THREAD

**Issue by caoliangliang19** [hydreamit/HyCharts#21]

**Comment by hydreamit** [comment]
更新实体数据源， 然后根据情况选择调用下面方法：

/// 数据整体渲染
- (void)setNeedsRendering;

/// 数据整体渲染及完成回调
- (void)setNeedsRenderingWithCompletion:(void(^ _Nullable)(void))completion;

/// 实时刷新最新价 或 添加/删除最前面数据 
- (void)refreshChartsView;
