### ISSUE TITLE
现在支持拖拽加载分页数据，想在缩放的时候也支持该怎么做？

### ISSUE THREAD

**Issue by LvMingfei** [hydreamit/HyCharts#24]

**Comment by hydreamit** [comment]
缩放分页加载时机 可以在缩放回调里 根据缩放方向和当前的偏移量来判断
相关api:

/// 缩放手势事件
@property (nonatomic, copy) void(^pinchGestureAction)(HyChartView *chartView, id<HyChartModelProtocol> model, NSUInteger index, CGFloat scale, UIGestureRecognizerState state);

/// 偏移量
@property (nonatomic, assign) CGFloat trans;

/// 图表内容宽度
@property (nonatomic, assign, readonly) CGFloat chartContentWidth;
