### ISSUE TITLE
折曲线图不支持小数吗？现在曲线各点  和y轴都是整数

### ISSUE THREAD

**Issue by kikilgm** [hydreamit/HyCharts#28]
折曲线图不支持小数吗？现在曲线各点  和y轴都是整数！能否加个小数的支持！

**Comment by hydreamit** [comment]
配置里面有
/// 精度
@property (nonatomic, assign) NSInteger decimal;
@property (nonatomic, strong, readonly) NSNumberFormatter *numberFormatter;

**Comment by kikilgm** [comment]
谢谢 大神。 不过还有个小问题，就是 如何让曲线图从顶点开始绘制 和X轴上的刻度 都从0 点开始。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "@***@***.***&gt;; 
发送时间: 2021年6月21日(星期一) 上午9:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hydreamit/HyCharts] 折曲线图不支持小数吗？现在曲线各点  和y轴都是整数 (#28)





 
配置里面有
 /// 精度
 @Property (nonatomic, assign) NSInteger decimal;
 @Property (nonatomic, strong, readonly) NSNumberFormatter *numberFormatter;
 
—
您收到此消息是因为您创作了该线程。
直接回复此邮件，在 GitHub 上查看，或取消订阅。
