### ISSUE TITLE
如何添加一条最新的数据和添加一个向之前时间分页加载的数组呢？

### ISSUE THREAD

**Issue by jimckylin** [hydreamit/HyCharts#29]
想要用http 分页加载之前的数据，和用socket加载最新的一条二条（或者几条）数据，请问要怎么做呢？

**Comment by jimckylin** [comment]
[self.klineView.dataSource.modelDataSource.models insertObject:model atIndex:0];
[self.klineView refreshChartsView];

这样添加最新的实现不了效果

**Comment by hydreamit** [comment]
refreshChartsView 会调用 model block数据源
添加删除模型数据 需要在model block数据源方法添加
- (instancetype)configNumberOfItems:(NSInteger(^)(void))block;
- (instancetype)configModelForItemAtIndex:(void (^_Nullable)(id<HyChartKLineModelProtocol> model, NSInteger index))block;
