### ISSUE TITLE
曲线图 如何让图表从X轴的0点开始绘制，并且X轴刻度也从0点开始？

### ISSUE THREAD

**Issue by kikilgm** [hydreamit/HyCharts#30]

**Comment by hydreamit** [comment]
图表从X轴的0点开始绘制：设置开始边距为0
/// 开始边距
@property (nonatomic, assign) CGFloat edgeInsetStart;

X轴刻度也从0点开始：X轴显示刻度 可以自定义
/// 每个坐标点对应的内容 (NSString NSAttributedString)
- (instancetype)configTextAtIndex:(id(^)(NSInteger index, id<HyChartModelProtocol> model))block;
