### ISSUE TITLE
关于小数点精度问题

### ISSUE THREAD

**Issue by mantoo96** [hydreamit/HyCharts#31]
你好大佬，一年过去了。
在实际应用中，etf这种指数因为差别很小比如1.117和1.116，可能都被model中的NSDecimalNumber方法弄成1.12，然后macd和ma就会变成很怪的线。这个地方我找不到在哪里修改得了

**Comment by hydreamit** [comment]
可以修改精度 或者 自定义格式化配置

/// 价格精度
@property (nonatomic, assign) NSInteger priceDecimal;
/// 价格格式转化器
@property (nonatomic, strong, readonly) NSNumberFormatter *priceNunmberFormatter;
