### ISSUE TITLE
k线怎么更新最新一个蜡烛柱

### ISSUE THREAD

**Issue by dongshangtong** [hydreamit/HyCharts#32]
您好，我想问一下，虚拟货币交易所k线，后台websocket 推送信息一个数据，怎么样去更新当前最新蜡烛柱和价格。

**Comment by woaiqiu947** [comment]
把最新的数据添加到HyChartsKLineDemoDataHandler 里的方法  configNumberOfItems: configModelForItemAtIndex: 中。
你可以保留之前的再添加新的 return array.count+newData.count;  
也可以只添加新的  return array.count

**Comment by dongshangtong** [comment]
还有个问题，当盘口价格波动，最后K线的蜡烛柱一直上下波动。一分钟40 至到 60 次波动。如果 更新最后一个数据，在去调用 configNumberOfItems: configModelForItemAtIndex: 。整k线页面很卡呀。
