### ISSUE TITLE
数据展示方向和数据顺序问题

### ISSUE THREAD

**Issue by mantoo96** [hydreamit/HyCharts#4]
HyChartDataDirectionReverse X轴逆向展示，数据数组翻转。最新价格的线也在最右边，配合滚动监听可以做到滑动加载
不过新股或者比较少数据的股票，怎么做到在数据少的时候从左边开始展示呢？  有什么实现思路吗？大佬

**Comment by hydreamit** [comment]
setNeedsRendering 之前判断设置下数据方向和坐标轴配置  数据少的标准可以根据图标内容宽度:chartContentWidth 和 图标试图宽度: chartWidth 来做判断

**Comment by mantoo96** [comment]
或者说，我该如何在x轴正向展示的时候，跳转到最后一条数据，就是滑动到最右这种方法。谢大佬回复啦
我已经把最新价改为最后一条数据的价格，同时在滑动时做了处理，永远都在缓存数组的前面加。所以剩下最后一个问题，就是第一次刷新是滚动到最右=，=
