### ISSUE TITLE
关于游标

### ISSUE THREAD

**Issue by mantoo96** [hydreamit/HyCharts#5]
demo里，组合图->K线组图，
self.klineCursor = HyChartsKLineDemoCursor.new;
self.klineCursor.showView = klineContentView;
[_klineMainView resetChartCursor:self.klineCursor];
只能显示在主图里，三个图分开设置又会出现定位不准的情况。副图怎么才能像K线图->K线那样联动3个图表呢？望解答

**Comment by mantoo96** [comment]
我的意思是，大佬你封装的K线图是包括三个图表，游标是联动的。K线主图和副图这种自定义组合怎么才能把游标也联动起来？

**Comment by hydreamit** [comment]
自由组合的图组，图表位置是外界自定义的，游标没办法统一，如果想实现统一只能自己处理了，可以把游标放在一个容器里，对游标位置进行坐标转换，注意手势滑动到图组之间的过渡间隙位置时根据你们需求做特殊处理
